export const questionArr = [
  [
    "JAVA-SCRIPT",
    `What is JavaScript?`,
    `1)JavaScript is a scripting language used to make the website interactive`,
    `2)JavaScript is an assembly language used to make the website interactive`,
    `3)JavaScript is a compiled language used to make the website interactive`,
    `4)None of the mentioned`,
    3,
  ],
  [
    "JAVA-SCRIPT",
    `Which of the following is correct about JavaScript?`,
    `1)JavaScript is an Object-Based language`,
    `2)JavaScript is Assembly-language`,
    `3)JavaScript is an Object-Oriented language`,
    `4)JavaScript is a High-level language`,
    1,
  ],
  [
    "JAVA-SCRIPT",
    `Among the given statements, which statement defines closures in JavaScript?`,
    `1)JavaScript is a function that is enclosed with references to its inner function scope`,
    `2)JavaScript is a function that is enclosed with references to its lexical environment`,
    `3)JavaScript is a function that is enclosed with the object to its inner function scope`,
    `4)None of the mentioned`,
    2,
  ],
  [
    "JAVA-SCRIPT",
    `Arrays in JavaScript are defined by which of the following statements?`,
    `1)It is an ordered list of values`,
    `2)It is an ordered list of objects`,
    `3)It is an ordered list of string`,
    `4)It is an ordered list of functions`,
    1,
  ],
  [
    "JAVA-SCRIPT",
    `Which of the following is not javascript data types?`,
    `1)Null type`,
    `2)Undefined type`,
    `3)Number type`,
    `4)All of the mentioned`,
    4,
  ],
  [
    "JAVA-SCRIPT",
    `Where is Client-side JavaScript code is embedded within HTML documents?`,
    `1)A URL that uses the special javascript:code`,
    `2)A URL that uses the special javascript:protocol`,
    `3)A URL that uses the special javascript:encoding`,
    `4) A URL that uses the special javascript:stack`,
    2,
  ],
  [
    "JAVA-SCRIPT",
    `Which of the following object is the main entry point to all client-side JavaScript features and APIs?`,
    `1)Position`,
    `2)Window`,
    `3)Standard`,
    `4)Location`,
    2,
  ],
  [
    "JAVA-SCRIPT",
    `Which of the following can be used to call a JavaScript Code Snippet?`,
    `1)Function/Method`,
    `2)Preprocessor`,
    `3)Triggering Event`,
    `4)RMI`,
    1,
  ],
  [
    "JAVA-SCRIPT",
    `Which of the following explains correctly what happens when a JavaScript program is developed on a Unix Machine?`,
    `1)will work perfectly well on a Windows Machine`,
    `2)will be displayed as JavaScript text on the browser`,
    `3)will throw errors and exceptions`,
    `4)must be restricted to a Unix Machine only`,
    1,
  ],
  [
    "JAVA-SCRIPT",
    `Which of the following scoping type does JavaScript use?`,
    `1)Sequential`,
    `2)Segmental`,
    `3)Lexical`,
    `4)Literal`,
    3,
  ],
  [
    "JAVA-SCRIPT",
    `What is the basic difference between JavaScript and Java?`,
    `1)Functions are considered as fields`,
    `2)Functions are values, and there is no hard distinction between methods and fields`,
    `3)Variables are specific`,
    `4)There is no difference`,
    2,
  ],
  [
    "JAVA-SCRIPT",
    `Why JavaScript Engine is needed?`,
    `1)Both Compiling & Interpreting the JavaScript`,
    `2)Parsing the javascript`,
    `3)Interpreting the JavaScript`,
    `4)Compiling the JavaScript`,
    3,
  ],
  [
    "JAVA-SCRIPT",
    `Which of the following methods/operation does javascript use instead of == and !=?`,
    `1)JavaScript uses equalto()`,
    `2)JavaScript uses equals() and notequals() instead`,
    `3)JavaScript uses bitwise checking`,
    `4)JavaScript uses === and !== instead`,
    4,
  ],
  [
    "JAVA-SCRIPT",
    `Why event handlers is needed in JS?`,
    `1)Allows JavaScript code to alter the behaviour of windows`,
    `2)Adds innerHTML page to the code`,
    `3)Change the server location`,
    `4)Performs handling of exceptions and occurrences`,
    1,
  ],
  [
    "JAVA-SCRIPT",
    `Which of the following is not a framework?`,
    `1)JavaScript .NET`,
    `2)JavaScript`,
    `3)Cocoa JS`,
    `4)jQuery`,
    2,
  ],
  [
    "EXPRESS.JS",
    `Who is credited as the developer of Express.js?`,
    `1)Larry wall`,
    `2)Rich Hickey`,
    `3)TJ Holowaychuk`,
    `4)Rob Pike`,
    3,
  ],
  [
    "EXPRESS.JS",
    `Which of the following are the core features of the Express framework? `,
    `1)It allows us to set up middleware to respond to HTTP Requests.`,
    `2)It defines a routing table that can work as per HTTP Method and URL.`,
    `3)It is used to render the HTML pages dynamically.`,
    `4)All of the above.`,
    4,
  ],
  [
    "EXPRESS.JS",
    `In which of the following year was Express.js initially released? `,
    `1)November 2010`,
    `2)November 2011`,
    `3)December 2010`,
    `4)December 2011`,
    1,
  ],
  [
    "EXPRESS.JS",
    ` What is the way to store local variables that can be accessed within the application?`,
    `1)Using Config file`,
    `2)Using database`,
    `3)Using app.locals`,
    `4)Using app.storage`,
    3,
  ],
  [
    "EXPRESS.JS",
    `In combination with a request method, root paths define the endpoints at which requests can be made. Which of the following are valid forms of route path?`,
    `1)strings`,
    `2)string patterns`,
    `3)regular expressions`,
    `4)All of the above`,
    4,
  ],
  [
    "EXPRESS.JS",
    `Where are the captured values populated regarding the route parameters? `,
    `1)req.data`,
    `2)app.locals`,
    `3)req.params`,
    `4)All of the above`,
    3,
  ],
  [
    "EXPRESS.JS",
    `How is it possible to create chainable route handlers for a route path in Express.js?`,
    `1)Using app.route()`,
    `2)Using app.routes()`,
    `3)Using app.router()`,
    `4)Using app.routing()`,
    1,
  ],
  [
    "EXPRESS.JS",
    `Which of the following function arguments are available to Express.js Route handlers?`,
    `1)req - the request object`,
    `2)res - the response object`,
    `3)next`,
    `4)All of the above`,
    4,
  ],
  [
    "EXPRESS.JS",
    `Which of the following is the Scaffolding in Express.js?`,
    `1)Yeoman`,
    `2)Express application generator`,
    `3)Handler functions`,
    `4)Both A & B`,
    4,
  ],
  [
    "EXPRESS.JS",
    `In Express.js, the method app.all(path, callback [, callback ...]) can accept all HTTP methods:`,
    `1)True`,
    `2)False`,
    `3)Insufficient data`,
    `4)None of the above`,
    1,
  ],
  [
    "EXPRESS.JS",
    `Which of the following is a middleware in Express.js?`,
    `1)function(req){ }`,
    `2)method(req){ }`,
    `3)function(req,res,next){ }`,
    `4)method(req,res,next){ }`,
    3,
  ],
  [
    "EXPRESS.JS",
    `Which of the following is the correct statement in the context of Express.js?`,
    `1)Express is a minimal and flexible Node.js web application framework.`,
    `2)Express is a minimal and flexible React.js web application framework.`,
    `3)Express is a minimal and flexible Redux.js web application framework.`,
    `4)Express is a minimal and flexible Angular.js web application framework.`,
    1,
  ],
  [
    "EXPRESS.JS",
    `Which of the following is the correct syntax to use Express.js in Node?`,
    `1)var = require('express')();`,
    `2)var_require('express')();`,
    `3)var app = require('express')();`,
    `4)None of the above.`,
    3,
  ],
  [
    "EXPRESS.JS",
    `What is the meaning of templating in Express.js?`,
    `1)Pug`,
    `2)EJS`,
    `3)Mustache`,
    `4)All of the above.`,
    4,
  ],
  [
    "EXPRESS.JS",
    `To use Mongo with Express.js, we need a client API for node.`,
    `1)TRUE`,
    `2)FALSE`,
    `3)Can be true or false`,
    `4)Cannot say`,
    1,
  ],
  [
    "SQL",
    `What is the full form of SQL?`,
    `1)Structured Query List`,
    `2)Structure Query Language`,
    `3)Sample Query Language`,
    `4)None of these.`,
    2,
  ],
  [
    "SQL",
    `Which of the following is not a valid SQL type?`,
    `1)FLOAT`,
    `2)NUMERIC`,
    `3)DECIMAL`,
    `4)CHARACTER`,
    3,
  ],
  [
    "SQL",
    `Which of the following are TCL commands?`,
    `1)COMMIT and ROLLBACK`,
    `2)UPDATE and TRUNCATE`,
    `3)SELECT and INSERT`,
    `4)GRANT and REVOKE`,
    1,
  ],
  [
    "SQL",
    `Which statement is used to delete all rows in a table without having the action logged?`,
    `1)DELETE`,
    `2)REMOVE`,
    `3)DROP`,
    `4)TRUNCATE`,
    4,
  ],
  [
    "SQL",
    `SQL Views are also known as`,
    `1)Simple tables`,
    `2)Virtual tables`,
    `3)Complex tables`,
    `4)Actual Tables`,
    2,
  ],
  [
    "SQL",
    `How many Primary keys can have in a table?`,
    `1)Only 1`,
    `2)Only 2`,
    `3)Depends on no of Columns`,
    `4)Depends on DBA`,
    1,
  ],
  [
    "SQL",
    `Which datatype can store unstructured data in a column?`,
    `1)CHAR`,
    `2)RAW`,
    `3)NUMERIC`,
    `4)VARCHAR`,
    2,
  ],
  [
    "SQL",
    `Which of the following is not Constraint in SQL?`,
    `1)Primary Key`,
    `2)Not Null`,
    `3)Check`,
    `4)Union`,
    4,
  ],
  [
    "SQL",
    `Which of the following is not a valid aggregate function?`,
    `1)COUNT`,
    `2)COMPUTE`,
    `3)SUM`,
    `4)MAX`,
    2,
  ],
  [
    "SQL",
    `Which data manipulation command is used to combines the records from one or more tables?`,
    `1)SELECT`,
    `2)PROJECT`,
    `3)JOIN`,
    `4)PRODUCT`,
    3,
  ],
  [
    "SQL",
    `Which operator is used to compare a value to a specified list of values?`,
    `1)ANY`,
    `2)BETWEEN`,
    `3)ALL`,
    `4)IN`,
    4,
  ],
  [
    "SQL",
    `What operator tests column for absence of data`,
    `1)NOT Operator`,
    `2)Exists Operator`,
    `3)IS NULL Operator`,
    `4)None of the above`,
    3,
  ],
  [
    "SQL",
    `In which of the following cases a DML statement is not executed?`,
    `1)When existing rows are modified.`,
    `2)When a table is deleted.`,
    `3)When some rows are deleted.`,
    `4)All of the above`,
    2,
  ],
  [
    "SQL",
    `If we have not specified ASC or DESC after a SQL ORDER BY clause, the following is used by default`,
    `1)DESC`,
    `2)ASC`,
    `3)There is no default value`,
    `4)None of the mentioned`,
    2,
  ],
  [
    "SQL",
    `Which of the following statement is true?`,
    `1)TRUNCATE free the table space while DELETE does not.`,
    `2)Both TRUNCATE and DELETE statements free the table's space.`,
    `3)Both TRUNCATE and DELETE statement does not free the table's space.`,
    `4)DELETE free the table space while TRUNCATE does not.`,
    1,
  ],
  [
    "NODE.JS",
    `Which of the following statement is correct?`,
    `1)js is Server Side Language.`,
    `2)js is the Client Side Language.`,
    `3)js is both Server Side and Client Side Language.`,
    `4)None of the above.`,
    1,
  ],
  [
    "NODE.JS",
    `What does the REPL stand for? `,
    `1)REPL stands for "Read Eval Print Loop."`,
    `2)REPL stands for "Research Eval Program Learn."`,
    `3)REPL stands for "Read Earn Point Learn."`,
    `4)REPL stands for "Read Eval Point Loop."`,
    1,
  ],
  [
    "NODE.JS",
    `Which of the following command is used to start a REPL session?`,
    `1)$ node`,
    `2)$ node start`,
    `3)$ node repl`,
    `4)$ node console`,
    1,
  ],
  [
    "NODE.JS",
    `Which of the following command is used to install the Node.js express module?`,
    `1)$ npm install express`,
    `2)$ node install express`,
    `3)$ install express`,
    `4)None of the above`,
    1,
  ],
  [
    "NODE.JS",
    `What is Callback?`,
    `1)The callback is a technique in which a method calls back the caller method.`,
    `2)The callback is an asynchronous equivalent for a function.`,
    `3)Both of the above.`,
    `4)None of the above.`,
    2,
  ],
  [
    "NODE.JS",
    `Which of the following extension is used to save the Node.js files?`,
    `1).js`,
    `2).node`,
    `3).java`,
    `4).txt`,
    1,
  ],
  [
    "NODE.JS",
    `The Node.js modules can be exposed using: `,
    `1)expose`,
    `2)module`,
    `3)exports`,
    `4)All of the above`,
    3,
  ],
  [
    "NODE.JS",
    `Which of the following module is not a built-in node module?`,
    `1)zlib`,
    `2)https`,
    `3)dgram`,
    `4)fsread`,
    4,
  ],
  [
    "NODE.JS",
    `Which of the following method of fs module is used to get file information?`,
    `1)fs.open(path, flags[, mode], callback)`,
    `2)fs.stat(path, callback)`,
    `3)fs.readFile(path, flags[, mode], callback)`,
    `4)None of the above.`,
    2,
  ],
  [
    "NODE.JS",
    `What does the fs module stand for?`,
    `1)File Service`,
    `2)File System`,
    `3)File Store`,
    `4)File Sharing`,
    2,
  ],
  [
    "NODE.JS",
    `Which of the following method of fs module is used to truncate a file?`,
    `1)fs.delete(fd, len, callback)`,
    `2)fs.remove(fd, len, callback)`,
    `3)fs.ftruncate(fd, len, callback)`,
    `4)None of the above.`,
    3,
  ],
  [
    "NODE.JS",
    `Which of the following template engines can be used with Node.js?`,
    `1)Jade`,
    `2)Vash`,
    `3)Handlebars`,
    `4)All of the above`,
    3,
  ],
  [
    "NODE.JS",
    `Which of the following code print the platform of operating system?`,
    `1)console.log('platform : ' + os.platform);`,
    `2)console.log('platform : ' + os.platform());`,
    `3)console.log('platform : ' + os.getPlatform());`,
    `4)None of the above.`,
    2,
  ],
  [
    "NODE.JS",
    `Which of the following method is used to return the current working directory of the process?`,
    `1)cwd();`,
    `2)cwd();`,
    `3)pwd();`,
    `4)None of the above.`,
    1,
  ],
  [
    "NODE.JS",
    `Which of the following statement defines Express?`,
    `1)Express is an application framework that provides a robust set of features to develop desktop-based applications.`,
    `2)Express is a minimal and flexible Node.js web application framework that provides a robust set of features to develop web and mobile applications.`,
    `3)Both of the above.`,
    `4)None of the above.`,
    2,
  ],
  [
    "GIT",
    `Which Command is used to show limited number of commits? `,
    `1)git fetch `,
    `2)git log -n .`,
    `3)git config `,
    `4)git status`,
    2,
  ],
  [
    "GIT",
    `Which command defines the author email to be used for all commits by the current user. `,
    `1)git clean -f `,
    `2)git config --global user.email .`,
    `3)git merge --no-ff `,
    `4)git email--amend`,
    2,
  ],
  [
    "GIT",
    `____________ command is useful for getting a high-level overview of the project history. `,
    `1)git log --oneline`,
    `2)git reset --hard.`,
    `3)git log --author=""`,
    `4)git rebase`,
    1,
  ],
  [
    "GIT",
    `___________________ removes untracked files from your working directory. `,
    `1)git commit`,
    `2)git clean -f .`,
    `3)git clean`,
    `4)git reset`,
    3,
  ],
  [
    "GIT",
    `Which command creates an empty Git repository in the specified directory? `,
    `1)git reset `,
    `2)git log ..`,
    `3)git init `,
    `4)git init --bare `,
    3,
  ],
  [
    "GIT",
    `Command to download all the objects and references from a specified repository `,
    `1)git config --list`,
    `2)git help .`,
    `3)git fetch `,
    `4)git log -n `,
    3,
  ],
  [
    "GIT",
    `Git command to compare two specified branches `,
    `1)git diff ...`,
    `2)git merge .`,
    `3)git blame -L , `,
    `4)git push --tags`,
    1,
  ],
  [
    "GIT",
    `_____________ command renames the current branch to <branch> `,
    `1)git remote rm `,
    `2)git branch -m .`,
    `3)git branch -D (CAPS)`,
    `4)git rebase`,
    2,
  ],
  [
    "GIT",
    `Which Git command displays the patch representing each commit. `,
    `1)git branch`,
    `2)git remote -v.`,
    `3)git log -p`,
    `4)git log`,
    3,
  ],
  [
    "GIT",
    ` Which of the following command line environment is used for interacting with Git ? `,
    `1)Git Bash`,
    `2)GitHub.`,
    `3)Git Boot`,
    `4)Git Lab`,
    1,
  ],
  [
    "GIT",
    `Ifyou want to make radical changes to your team's project and don't want to impact the rest of the team, you should implement your changes in - `,
    `1)the root`,
    `2)a tag.`,
    `3)the trunk`,
    `4)None of the above`,
    4,
  ],
  [
    "GIT",
    `The Git clone command does which of the following? `,
    `1)Makes a local copy of the repository`,
    `2)Creates a working directory.`,
    `3)Commits a new branch`,
    `4)Both 1 & 2`,
    4,
  ],
  [
    "GIT",
    `Which one of the following is not part of the data structure of a Git repository? `,
    `1)Branch pointer`,
    `2)Body element.`,
    `3)Commit object`,
    `4)Head pointer`,
    2,
  ],
  [
    "GIT",
    `Which of these Git client commands creates a copy of the repository and a working directory in the client's workspace. `,
    `1)checkout`,
    `2)clone.`,
    `3)import`,
    `4)update`,
    2,
  ],
  [
    "GIT",
    `GIT belongs to the............. generation of Version Control tools `,
    `1)2nd`,
    `2)3rd.`,
    `3)4th`,
    `4)5th`,
    2,
  ],
];
