 questionRecords = [
  {
    category:"JAVA-SCRIPT",
    question:`What is JavaScript?`,
    test1:`1)JavaScript is a scripting language used to make the website interactive`,
    test2: `2)JavaScript is an assembly language used to make the website interactive`,
    test3:`3)JavaScript is a compiled language used to make the website interactive`,
    test4:`4)None of the mentioned`,
    answer:3
  },
  {
    category:"JAVA-SCRIPT",
    question:`Which of the following is correct about JavaScript?`,
    test1:`1)JavaScript is an Object-Based language`,
    test2:`2)JavaScript is Assembly-language`,
    test3:`3)JavaScript is an Object-Oriented language`,
    test4:`4)JavaScript is a High-level language`,
    answer:1,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Among the given statements, which statement defines closures in JavaScript?`,
    test1:`1)JavaScript is a function that is enclosed with references to its inner function scope`,
    test2:`2)JavaScript is a function that is enclosed with references to its lexical environment`,
    test3:`3)JavaScript is a function that is enclosed with the object to its inner function scope`,
    test4:`4)None of the mentioned`,
    answer:2,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Arrays in JavaScript are defined by which of the following statements?`,
    test1 : `1)It is an ordered list of values`,
    test2:`2)It is an ordered list of objects`,
    test3:`3)It is an ordered list of string`,
    test4:`4)It is an ordered list of functions`,
    answer:1,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Which of the following is not javascript data types?`,
    test1 : `1)Null type`,
    test2 : `2)Undefined type`,
    test3: `3)Number type`,
    test4: `4)All of the mentioned`,
    answer : 4,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Where is Client-side JavaScript code is embedded within HTML documents?`,
    test1 : `1)A URL that uses the special javascript:code`,
    test2 : `2)A URL that uses the special javascript:protocol`,
    test3: `3)A URL that uses the special javascript:encoding`,
    test4: `4) A URL that uses the special javascript:stack`,
    answer : 2,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Which of the following object is the main entry point to all client-side JavaScript features and APIs?`,
    test1 : `1)Position`,
    test2 : `2)Window`,
    test3: `3)Standard`,
    test4: `4)Location`,
    answer : 2,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Which of the following can be used to call a JavaScript Code Snippet?`,
    test1 : `1)Function/Method`,
    test2 : `2)Preprocessor`,
    test3: `3)Triggering Event`,
    test4: `4)RMI`,
    answer : 1,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Which of the following explains correctly what happens when a JavaScript program is developed on a Unix Machine?`,
    test1 : `1)will work perfectly well on a Windows Machine`,
    test2 : `2)will be displayed as JavaScript text on the browser`,
    test3: `3)will throw errors and exceptions`,
    test4: `4)must be restricted to a Unix Machine only`,
    answer : 1,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Which of the following scoping type does JavaScript use?`,
    test1 : `1)Sequential`,
    test2 : `2)Segmental`,
    test3: `3)Lexical`,
    test4: `4)Literal`,
    answer : 3,
  },
  {
    category:"JAVA-SCRIPT",
    question:`What is the basic difference between JavaScript and Java?`,
    test1 : `1)Functions are considered as fields`,
    test2 : `2)Functions are values, and there is no hard distinction between methods and fields`,
    test3: `3)Variables are specific`,
    test4: `4)There is no difference`,
    answer : 2,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Why JavaScript Engine is needed?`,
    test1 : `1)Both Compiling & Interpreting the JavaScript`,
    test2 : `2)Parsing the javascript`,
    test3: `3)Interpreting the JavaScript`,
    test4: `4)Compiling the JavaScript`,
    answer : 3,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Which of the following methods/operation does javascript use instead of == and !=?`,
    test1 : `1)JavaScript uses equalto()`,
    test2 : `2)JavaScript uses equals() and notequals() instead`,
    test3: `3)JavaScript uses bitwise checking`,
    test4: `4)JavaScript uses === and !== instead`,
    answer : 4,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Why event handlers is needed in JS?`,
    test1 : `1)Allows JavaScript code to alter the behaviour of windows`,
    test2 : `2)Adds innerHTML page to the code`,
    test3: `3)Change the server location`,
    test4: `4)Performs handling of exceptions and occurrences`,
    answer : 1,
  },
  {
    category:"JAVA-SCRIPT",
    question:`Which of the following is not a framework?`,
    test1 : `1)JavaScript .NET`,
    test2 : `2)JavaScript`,
    test3: `3)Cocoa JS`,
    test4: `4)jQuery`,
    answer : 2,
  },
  {
    category:"EXPRESS.JS",
    question:`Who is credited as the developer of Express.js?`,
    test1 : `1)Larry wall`,
    test2 : `2)Rich Hickey`,
    test3: `3)TJ Holowaychuk`,
    test4: `4)Rob Pike`,
    answer : 3,
  },
  {
    category:"EXPRESS.JS",
    question:`Which of the following are the core features of the Express framework? `,
    test1 : `1)It allows us to set up middleware to respond to HTTP Requests.`,
    test2 : `2)It defines a routing table that can work as per HTTP Method and URL.`,
    test3: `3)It is used to render the HTML pages dynamically.`,
    test4: `4)All of the above.`,
    answer : 4,
  },
  {
    category:"EXPRESS.JS",
    question:`In which of the following year was Express.js initially released? `,
    test1 : `1)November 2010`,
    test2 : `2)November 2011`,
    test3: `3)December 2010`,
    test4: `4)December 2011`,
    answer : 1,
  },
  {
    category:"EXPRESS.JS",
    question:` What is the way to store local variables that can be accessed within the application?`,
    test1 : `1)Using Config file`,
    test2 : `2)Using database`,
    test3: `3)Using app.locals`,
    test4: `4)Using app.storage`,
    answer : 3,
  },
  {
    category:"EXPRESS.JS",
    question:`In combination with a request method, root paths define the endpoints at which requests can be made. Which of the following are valid forms of route path?`,
    test1 : `1)strings`,
    test2 : `2)string patterns`,
    test3: `3)regular expressions`,
    test4: `4)All of the above`,
    answer : 4,
  },
  {
    category:"EXPRESS.JS",
    question:`Where are the captured values populated regarding the route parameters? `,
    test1 : `1)req.data`,
    test2 : `2)app.locals`,
    test3: `3)req.params`,
    test4: `4)All of the above`,
    answer : 3,
  },
  {
    category:"EXPRESS.JS",
    question:`How is it possible to create chainable route handlers for a route path in Express.js?`,
    test1 : `1)Using app.route()`,
    test2 : `2)Using app.routes()`,
    test3: `3)Using app.router()`,
    test4: `4)Using app.routing()`,
    answer : 1,
  },
  {
    category:"EXPRESS.JS",
    question:`Which of the following function arguments are available to Express.js Route handlers?`,
    test1 : `1)req - the request object`,
    test2 : `2)res - the response object`,
    test3: `3)next`,
    test4: `4)All of the above`,
    answer : 4,
  },
  {
    category:"EXPRESS.JS",
    question:`Which of the following is the Scaffolding in Express.js?`,
    test1 : `1)Yeoman`,
    test2 : `2)Express application generator`,
    test3: `3)Handler functions`,
    test4: `4)Both A & B`,
    answer : 4,
  },
  {
    category:"EXPRESS.JS",
    question:`In Express.js, the method app.all(path, callback {, callback ...}) can accept all HTTP methods:`,
    test1 : `1)True`,
    test2 : `2)False`,
    test3: `3)Insufficient data`,
    test4: `4)None of the above`,
    answer : 1,
  },
  {
    category:"EXPRESS.JS",
    question:`Which of the following is a middleware in Express.js?`,
    test1 : `1)function(req){ }`,
    test2 : `2)method(req){ }`,
    test3: `3)function(req,res,next){ }`,
    test4: `4)method(req,res,next){ }`,
    answer : 3,
  },
  {
    category:"EXPRESS.JS",
    question:`Which of the following is the correct statement in the context of Express.js?`,
    test1 : `1)Express is a minimal and flexible Node.js web application framework.`,
    test2 : `2)Express is a minimal and flexible React.js web application framework.`,
    test3: `3)Express is a minimal and flexible Redux.js web application framework.`,
    test4: `4)Express is a minimal and flexible Angular.js web application framework.`,
    answer : 1,
  },
  {
    category:"EXPRESS.JS",
    question:`Which of the following is the correct syntax to use Express.js in Node?`,
    test1 : `1)var = require('express')();`,
    test2 : `2)var_require('express')();`,
    test3: `3)var app = require('express')();`,
    test4: `4)None of the above.`,
    answer : 3,
  },
  {
    category:"EXPRESS.JS",
    question:`What is the meaning of templating in Express.js?`,
    test1 : `1)Pug`,
    test2 : `2)EJS`,
    test3: `3)Mustache`,
    test4: `4)All of the above.`,
    answer : 4,
  },
  {
    category:"EXPRESS.JS",
    question:`To use Mongo with Express.js, we need a client API for node.`,
    test1 : `1)TRUE`,
    test2 : `2)FALSE`,
    test3: `3)Can be true or false`,
    test4: `4)Cannot say`,
    answer : 1,
  },
  {
    category:"SQL",
    question:`What is the full form of SQL?`,
    test1 : `1)Structured Query List`,
    test2 : `2)Structure Query Language`,
    test3: `3)Sample Query Language`,
    test4: `4)None of these.`,
    answer : 2,
  },
  {
    category:"SQL",
    question:`Which of the following is not a valid SQL type?`,
    test1 : `1)FLOAT`,
    test2 : `2)NUMERIC`,
    test3: `3)DECIMAL`,
    test4: `4)CHARACTER`,
    answer : 3,
  },
  {
    category:"SQL",
    question:`Which of the following are TCL commands?`,
    test1 : `1)COMMIT and ROLLBACK`,
    test2 : `2)UPDATE and TRUNCATE`,
    test3: `3)SELECT and INSERT`,
    test4: `4)GRANT and REVOKE`,
    answer : 1,
  },
  {
    category:"SQL",
    question:`Which statement is used to delete all rows in a table without having the action logged?`,
    test1 : `1)DELETE`,
    test2 : `2)REMOVE`,
    test3: `3)DROP`,
    test4: `4)TRUNCATE`,
    answer : 4,
  },
  {
    category:"SQL",
    question:`SQL Views are also known as`,
    test1 : `1)Simple tables`,
    test2 : `2)Virtual tables`,
    test3: `3)Complex tables`,
    test4: `4)Actual Tables`,
    answer : 2,
  },
  {
    category:"SQL",
    question:`How many Primary keys can have in a table?`,
    test1 : `1)Only 1`,
    test2 : `2)Only 2`,
    test3: `3)Depends on no of Columns`,
    test4: `4)Depends on DBA`,
    answer : 1,
  },
  {
    category:"SQL",
    question:`Which datatype can store unstructured data in a column?`,
    test1 : `1)CHAR`,
    test2 : `2)RAW`,
    test3: `3)NUMERIC`,
    test4: `4)VARCHAR`,
    answer : 2,
  },
  {
    category:"SQL",
    question:`Which of the following is not Constraint in SQL?`,
    test1 : `1)Primary Key`,
    test2 : `2)Not Null`,
    test3: `3)Check`,
    test4: `4)Union`,
    answer : 4,
  },
  {
    category:"SQL",
    question:`Which of the following is not a valid aggregate function?`,
    test1 : `1)COUNT`,
    test2 : `2)COMPUTE`,
    test3: `3)SUM`,
    test4: `4)MAX`,
    answer : 2,
  },
  {
    category:"SQL",
    question:`Which data manipulation command is used to combines the records from one or more tables?`,
    test1 : `1)SELECT`,
    test2 : `2)PROJECT`,
    test3: `3)JOIN`,
    test4: `4)PRODUCT`,
    answer : 3,
  },
  {
    category:"SQL",
    question:`Which operator is used to compare a value to a specified list of values?`,
    test1 : `1)ANY`,
    test2 : `2)BETWEEN`,
    test3: `3)ALL`,
    test4: `4)IN`,
    answer : 4,
  },
  {
    category:"SQL",
    question:`What operator tests column for absence of data`,
    test1:`1)NOT Operator`,
    test1:`2)Exists Operator`,
    test1:`3)IS NULL Operator`,
    test1:`4)None of the above`,
    answer : 3,
  },
  {
    category:"SQL",
    question:`In which of the following cases a DML statement is not executed?`,
    test1:`1)When existing rows are modified.`,
    test2 : `2)When a table is deleted.`,
    test3 : `3)When some rows are deleted.`,
    test4 : `4)All of the above`,
    answer : 2,
  },
  {
    category:"SQL",
    question:`If we have not specified ASC or DESC after a SQL ORDER BY clause, the following is used by default`,
    test1 : `1)DESC`,
    test2 : `2)ASC`,
    test3 : `3)There is no default value`,
    test4 : `4)None of the mentioned`,
    answer : 2,
  },
  {
    category:"SQL",
    question:`Which of the following statement is true?`,
    test1 : `1)TRUNCATE free the table space while DELETE does not.`,
    test2 : `2)Both TRUNCATE and DELETE statements free the table's space.`,
    test3 : `3)Both TRUNCATE and DELETE statement does not free the table's space.`,
    test4 : `4)DELETE free the table space while TRUNCATE does not.`,
    answer : 1,
  },
  {
    category:"NODE.JS",
    question:`Which of the following statement is correct?`,
    test1 : `1)js is Server Side Language.`,
    test2 : `2)js is the Client Side Language.`,
    test3 : `3)js is both Server Side and Client Side Language.`,
    test4 : `4)None of the above.`,
    answer : 1,
  },
  {
    category:"NODE.JS",
    question:`What does the REPL stand for? `,
    test1 : `1)REPL stands for "Read Eval Print Loop."`,
    test2 : `2)REPL stands for "Research Eval Program Learn."`,
    test3 : `3)REPL stands for "Read Earn Point Learn."`,
    test4 : `4)REPL stands for "Read Eval Point Loop."`,
    answer : 1,
  },
  {
    category:"NODE.JS",
    question:`Which of the following command is used to start a REPL session?`,
    test1 : `1)$ node`,
    test2 : `2)$ node start`,
    test3 : `3)$ node repl`,
    test4 : `4)$ node console`,
    answer : 1,
  },
  {
    category:"NODE.JS",
    question:`Which of the following command is used to install the Node.js express module?`,
    test1 : `1)$ npm install express`,
    test2 : `2)$ node install express`,
    test3 : `3)$ install express`,
    test4 : `4)None of the above`,
    answer : 1,
  },
  {
    category:"NODE.JS",
    question:`What is Callback?`,
    test1 : `1)The callback is a technique in which a method calls back the caller method.`,
    test2 : `2)The callback is an asynchronous equivalent for a function.`,
    test3 : `3)Both of the above.`,
    test4 : `4)None of the above.`,
    answer : 2,
  },
  {
    category:"NODE.JS",
    question:`Which of the following extension is used to save the Node.js files?`,
    test1 : `1).js`,
    test2 : `2).node`,
    test3 : `3).java`,
    test4 : `4).txt`,
    answer : 1,
  },
  {
    category:"NODE.JS",
    question:`The Node.js modules can be exposed using: `,
    test1 : `1)expose`,
    test2 : `2)module`,
    test3 : `3)exports`,
    test4 : `4)All of the above`,
    answer : 3,
  },
  {
    category:"NODE.JS",
    question:`Which of the following module is not a built-in node module?`,
    test1 : `1)zlib`,
    test2 : `2)https`,
    test3 : `3)dgram`,
    test4 : `4)fsread`,
    answer : 4,
  },
  {
    category:"NODE.JS",
    question:`Which of the following method of fs module is used to get file information?`,
    test1 : `1)fs.open(path, flags{, mode}, callback)`,
    test2 : `2)fs.stat(path, callback)`,
    test3 : `3)fs.readFile(path, flags{, mode}, callback)`,
    test4 : `4)None of the above.`,
    answer : 2,
  },
  {
    category:"NODE.JS",
    question:`What does the fs module stand for?`,
    test1 : `1)File Service`,
    test2 : `2)File System`,
    test3: `3)File Store`,
    test4: `4)File Sharing`,
    answer : 2,
  },
  {
    category:"NODE.JS",
    question:`Which of the following method of fs module is used to truncate a file?`,
    test1 : `1)fs.delete(fd, len, callback)`,
    test2 : `2)fs.remove(fd, len, callback)`,
    test3: `3)fs.ftruncate(fd, len, callback)`,
    test4: `4)None of the above.`,
    answer : 3,
  },
  {
    category:"NODE.JS",
    question:`Which of the following template engines can be used with Node.js?`,
    test1 : `1)Jade`,
    test2 : `2)Vash`,
    test3: `3)Handlebars`,
    test4: `4)All of the above`,
    answer : 3,
  },
  {
    category:"NODE.JS",
    question:`Which of the following code print the platform of operating system?`,
    test1 : `1)console.log('platform : ' + os.platform);`,
    test2 : `2)console.log('platform : ' + os.platform());`,
    test3: `3)console.log('platform : ' + os.getPlatform());`,
    test4: `4)None of the above.`,
    answer : 2,
  },
  {
    category:"NODE.JS",
    question:`Which of the following method is used to return the current working directory of the process?`,
    test1 : `1)cwd();`,
    test2 : `2)cwd();`,
    test3: `3)pwd();`,
    test4: `4)None of the above.`,
    answer : 1,
  },
  {
    category:"NODE.JS",
    question:`Which of the following statement defines Express?`,
    test1 : `1)Express is an application framework that provides a robust set of features to develop desktop-based applications.`,
    test2 : `2)Express is a minimal and flexible Node.js web application framework that provides a robust set of features to develop web and mobile applications.`,
    test3: `3)Both of the above.`,
    test4: `4)None of the above.`,
    answer : 2,
  },
  {
    category:"GIT",
    question:`Which Command is used to show limited number of commits? `,
    test1 : `1)git fetch `,
    test2 : `2)git log -n .`,
    test3: `3)git config `,
    test4: `4)git status`,
    answer : 2,
  },
  {
    category:"GIT",
    question:`Which command defines the author email to be used for all commits by the current user. `,
    test1 : `1)git clean -f `,
    test2 : `2)git config --global user.email .`,
    test3: `3)git merge --no-ff `,
    test4: `4)git email--amend`,
    answer : 2,
  },
  {
    category:"GIT",
    question:`____________ command is useful for getting a high-level overview of the project history. `,
    test1 : `1)git log --oneline`,
    test2 : `2)git reset --hard.`,
    test3: `3)git log --author=""`,
    test4: `4)git rebase`,
    answer : 1,
  },
  {
    category:"GIT",
    question:`___________________ removes untracked files from your working directory. `,
    test1 : `1)git commit`,
    test2 : `2)git clean -f .`,
    test3: `3)git clean`,
    test4: `4)git reset`,
    answer : 3,
  },
  {
    category:"GIT",
    question:`Which command creates an empty Git repository in the specified directory? `,
    test1 : `1)git reset `,
    test2 : `2)git log ..`,
    test3: `3)git init `,
    test4: `4)git init --bare `,
    answer : 3,
  },
  {
    category:"GIT",
    question:`Command to download all the objects and references from a specified repository `,
    test1 : `1)git config --list`,
    test2 : `2)git help .`,
    test3: `3)git fetch `,
    test4: `4)git log -n `,
    answer : 3,
  },
  {
    category:"GIT",
    question:`Git command to compare two specified branches `,
    test1 : `1)git diff ...`,
    test2 : `2)git merge .`,
    test3: `3)git blame -L , `,
    test4: `4)git push --tags`,
    answer : 1,
  },
  {
    category:"GIT",
    question:`_____________ command renames the current branch to <branch> `,
    test1 : `1)git remote rm `,
    test2 : `2)git branch -m .`,
    test3: `3)git branch -D (CAPS)`,
    test4: `4)git rebase`,
    answer : 2,
  },
  {
    category:"GIT",
    question:`Which Git command displays the patch representing each commit. `,
    test1 : `1)git branch`,
    test2 : `2)git remote -v.`,
    test3: `3)git log -p`,
    test4: `4)git log`,
    answer : 3,
  },
  {
    category:"GIT",
    question:` Which of the following command line environment is used for interacting with Git ? `,
    test1 : `1)Git Bash`,
    test2 : `2)GitHub.`,
    test3: `3)Git Boot`,
    test4: `4)Git Lab`,
    answer : 1,
  },
  {
    category:"GIT",
    question:`Ifyou want to make radical changes to your team's project and don't want to impact the rest of the team, you should implement your changes in - `,
    test1 : `1)the root`,
    test2 : `2)a tag.`,
    test3: `3)the trunk`,
    test4: `4)None of the above`,
    answer : 4,
  },
  {
    category:"GIT",
    question:`The Git clone command does which of the following? `,
    test1 : `1)Makes a local copy of the repository`,
    test2 : `2)Creates a working directory.`,
    test3: `3)Commits a new branch`,
    test4: `4)Both 1 & 2`,
    answer : 4,
  },
  {
    category:"GIT",
    question:`Which one of the following is not part of the data structure of a Git repository? `,
    test1 : `1)Branch pointer`,
    test2 : `2)Body element.`,
    test3: `3)Commit object`,
    test4: `4)Head pointer`,
    answer : 2,
  },
  {
    category:"GIT",
    question:`Which of these Git client commands creates a copy of the repository and a working directory in the client's workspace. `,
    test1 : `1)checkout`,
    test2 : `2)clone.`,
    test3: `3)import`,
    test4: `4)update`,
    answer : 2,
  },
  {
    category:"GIT",
    question:`GIT belongs to the............. generation of Version Control tools `,
    test1 : `1)2nd`,
    test2 : `2)3rd.`,
    test3: `3)4th`,
    test4: `4)5th`,
    answer : 2,
  },
];
module.exports = {questionRecords};